### ISSUE TITLE
Stops working for more than 20 named shadows

### ISSUE THREAD

**Issue by marc-enseo** [aws-greengrass/aws-greengrass-shadow-manager#120] opened 2022-03-23 19:07 UTC
**Describe the bug**
This was posted initially in the AWS forum but we are experiencing the same issue.  As soon as I add more devices, i.e. the named shadows go over some limit (about 20 or so), a bunch of errors appear in the log and shadow manager stops working. Logs are below. If I modify the shadow manager config to sync 1 device less, everything works perfectly again. Also this has nothing to do with any of my python code or the sdk. To check, I've completely removed my custom component and have just nucleus, cli and shadowmanager running and still get these errors in the log with the same behavior. The errors seem to be related to mqtt.

See https://forums.aws.amazon.com/thread.jspa?threadID=348616

**Additional context**
We have an environment with hundreds of devices connected to the cloud via GG core.

**Comment by marc-enseo** [comment] 2022-03-23 19:08
We are an AWS business customer with paid support.  Case ID 9782302381 was filed for this issue.

**Comment by marc-enseo** [comment] 2022-03-24 17:29
Hi Nikkil,

We are using all the latest.  Nucleo/Core 2.5.3.  ShadowManager 2.1.0.

**Comment by nikkhilmuthye** [comment] 2022-03-24 17:54
So when you said the issue seems to be related to MQTT, can you provide the logs? Right now Shadow is not integrated with MQTT. Unless you had a custom component to integrate shadow and client devices, client devices cannot perform shadow operations with the current version.

**Comment by marc-enseo** [comment] 2022-03-24 21:17
All shadows stop working.  Then it just starts spewing...

**Comment by jbutler** [comment] 2022-03-24 23:24
While we work on trying to reproduce this, one thing you can try is enabling IoT Core logging to see what is going on from the cloud perspective. There are several reasons the cloud may be disconnecting Greengrass. The 50 subscription limit is one, but Nucleus has logic to handle that. Incorrect permissions is another common reason.

https://docs.aws.amazon.com/iot/latest/developerguide/configure-logging.html

**Comment by marc-enseo** [comment] 2022-03-25 04:41
We do have all logging enabled.  It all works when we have a few subscriptions but definitely break when we start ramping up the number of subscriptions.

**Comment by MikeDombo** [comment] 2022-05-18 18:45
@marc-enseo, to provide you with an update, https://github.com/aws-greengrass/aws-greengrass-nucleus/pull/1192 fixes the issue you were encountering. It is currently planned to be released in Nucleus version 2.5.6 which is currently planned for release at the end of the month. The date may change but I just want to keep you informed.

**Comment by MikeDombo** [comment] 2022-06-03 18:26
Fix has been releaed as Nucleus 2.5.6 now available. 

Closing this issue. Please reopen with a comment if necessary.

**Closed** 2022-06-03 18:27 UTC
Labels: bug
