### ISSUE TITLE
Wildcard support for thingName

### ISSUE THREAD

**Issue by evergreendrose** [aws-greengrass/aws-greengrass-shadow-manager#118] opened 2022-02-27 10:39 UTC
For authorization I am trying to use a variable for thingName within the resource. I am unsure of how to authorize the device otherwise as I would need a component for each device that specifics the exact thing name. Can you advise a different approach for deploying a component that will interact with many things

**Comment by evergreendrose** [comment] 2022-02-28 03:18
Figured this out using --update-config --merge

**Comment by nikkhilmuthye** [comment] 2022-03-02 19:41
Hi @evergreendrose,

Can you provide more information on the issue that you faced and what configuration did you merge in to fix it?

Thanks,
Nikkhil

**Comment by evergreendrose** [comment] 2022-03-02 20:47
So high level:

You have some resource (a thing) you want to give perms to within a component. But for shadows it must be defined exactly and currently there's no way to use {iot:thingName} variable in the recipe.

So deploy recipe with a generic config, and the immediataly deploy a local change to that recipe where resource is device name. Essenitally a script that changes the recipe once its on the thing. 

something like this
`sudo greengrass-cli deployment create \
  --recipeDir recipes \
  --artifactDir artifacts \
  --merge "com.example.IndustrialDashboard=1.0.0" \
  --update-config dashboard-configuration.json
`
where dashboard-configuration.json is
{
  "com.example.IndustrialDashboard": {
    "MERGE": {
      "name": "Factory 2A",
      "network": {
        "useHttps": false,
        "port": {
          "http": 8080
        }
      },
      "tags": [
        "/boiler/1/temperature",
        "/boiler/1/pressure",
        "/boiler/2/temperature",
        "/boiler/2/pressure"
      ]
    }
  }
}

**Comment by evergreendrose** [comment] 2022-03-09 00:38
I am still struggling now because once I do a local deployment it wont let me override with a new deployment from cloud. Any guidance?

**Comment by MikeDombo** [comment] 2022-03-09 00:45
Hi @evergreendrose,
In what way does it not let you override? Deployment configuration is merged by timestamp, the later timestamp will take precedence.

If the deployment fails due to component version conflict, then create a local deployment to _remove_ the components using `deployment create --remove <component name>"

**Comment by evergreendrose** [comment] 2022-03-09 01:09
Hey @MikeDombo 
Thanks for the prompt reply. I'm trying to deploy devices at scale so it's not feasible to remove the deployment on each device.

Currently I am including a merge action in my script in order to utilize the local thing name in my resource configuration for shadow manager.

But then I cannot deploy a new version.

What your saying makes sense on an individual basis but not sure how I'd do that programmatically.

Maybe another component that removes it?

**Comment by MikeDombo** [comment] 2022-03-09 01:12
I'm not clear on what the problem is. Can you please clarify your statement "it wont let me override with a new deployment from cloud"

**Comment by evergreendrose** [comment] 2022-03-09 02:42
@MikeDombo 
I am looking to deploy shadow manager to a thing group, in order to do so it needs specific permissions in the recipe. Which i identity with the resource that looks like $aws/thing/mything/shadow

From what i understand the recipe resource cannot contain a variable (ie. {iot:thingName}. So i am just passing in $aws/thing/*/shadow

I am trying to solve the problem of getting each thing name into its respective recipe.

My current solution is to deploy the component with a script that merges the thing name into the recipe. Now when i go to update it via group deployment on the console, the update does not complete because the version is different on the local deployment. So it seems removing that local deployment would allow me to deploy a new version.

**Comment by MikeDombo** [comment] 2022-03-09 02:49
For your current problem, yes, do a local deployment to remove the components from the "local" group.

I'm still a bit confused about what you're doing with regard to creating different recipes. Your recipes should apply equally to all of your devices. Then, in a deployment targeting the individual thing, you can set the configuration for that particular device (https://docs.aws.amazon.com/greengrass/v2/developerguide/update-component-configurations.html#merge-configuration-update).

**Comment by evergreendrose** [comment] 2022-03-09 03:00
Got it, doesnt need to be local deployment, makes sense. 

I will try that now. Appreciate it.

**Comment by vaibhavmurkute** [comment] 2022-03-17 01:24
Closing this issue, please feel free to reopen if there is something to discuss on this issue. Thanks.

**Closed by vaibhavmurkute** 2022-03-17 01:24 UTC

**Comment by hacor** [comment] 2022-03-17 11:16
Hello!

I'm sorry to reopen this topic, but I think I'm facing the same design problem with the Shadow Manager.
My current setup:
- I have a rPi 4 setup as a `Greengrass core` device. 
- The end user should be able to add `things` to this core device (e.g. zigbee outlets)
- A custom component manages the power metering of the things and send the results to `IoT Analytics` using Stream Manager
- The greengrass core is running the `aws.greengrass.ShadowManager` component through a console-managed thing-group deployment

Now my design concept would be the following:
- The user wants to add/connect a new device `newThingName` to the core
- A custom component in the core device adds the new thing, policy, certificate,... in AWS IoT and associates `newThingName` to this greengrass core device.
- Now I need to update the `Shadow Manager` component, so it syncs the classic shadow of `newThingName` as well. If I update my current global deployment, all core devices will be syncing this new thing and that's not my intention of course.

I thought of a few ways to realise what I want:
- I was hoping to be able to use the [updateConfigRequest](https://aws.github.io/aws-iot-device-sdk-python-v2/awsiot/greengrasscoreipc.html#awsiot.greengrasscoreipc.model.UpdateConfigurationRequest) from the Python IoT device SDK in order to dynamically change the Shadow Manager configuration. But this function seems only capable of changing its own configuration (the component running it)
- Add a new option to the `synchronize` configuration parameter of the `Shadow Manager` configuration: `syncAssociatedThings: true`. If a new thing is associated to the core device, the Shadow manager automatically picks this up and adds it to the sync list.
- Add an option to the `synchronize` parameter of the `Shadow Manager` configuration to sync all thing shadows from things who are member of a group. If a new thing is added to the group, shadow manager also syncs this shadow.
- The availability to add following wildcard configuration option to the `Shadow Manager` component. If I rename all things to _coreDevice_-_newThingName_ it would work perfectly.
```json
{
  "synchronize": {
    "shadowDcouments": {
        "thingName": "coreDevice*"
    }
  }
} 
```

But from what I read here I'm thinking my approach is wrong. From what I read here the following flow would be more correct:
- Every core device runs a global deployment containing all AWS components who don't need local reconfiguration.
- Every core device has a second, local-oriented deployment containing the components (`Shadow Manager` in this case) that differ in configuration.

To add a new thing, I do exactly as before, but instead of updating the _configuration_, I create a deployment merge update for the local deployment of this device.
Dit I understood correctly?

Thanks!
Best regards

Hacor
